launch:
  # behavior path modules
  - arg:
      name: launch_avoidance_module
      default: "true"
  - arg:
      name: launch_avoidance_by_lane_change_module
      default: "true"
  - arg:
      name: launch_dynamic_avoidance_module
      default: "false"
  - arg:
      name: launch_lane_change_right_module
      default: "true"
  - arg:
      name: launch_lane_change_left_module
      default: "true"
  - arg:
      name: launch_external_request_lane_change_right_module
      default: "false"
  - arg:
      name: launch_external_request_lane_change_left_module
      default: "false"
  - arg:
      name: launch_goal_planner_module
      default: "true"
  - arg:
      name: launch_start_planner_module
      default: "true"
  - arg:
      name: launch_side_shift_module
      default: "true"
  - arg:
      name: use_experimental_lane_change_function
      default: "true"

  # behavior velocity modules
  - arg:
      name: launch_crosswalk_module
      default: "true"
  - arg:
      name: launch_walkway_module
      default: "true"
  - arg:
      name: launch_traffic_light_module
      default: "true"
  - arg:
      name: launch_intersection_module
      default: "true"
  - arg:
      name: launch_merge_from_private_module
      default: "true"
  - arg:
      name: launch_blind_spot_module
      default: "true"
  - arg:
      name: launch_detection_area_module
      default: "true"
  - arg:
      name: launch_virtual_traffic_light_module
      default: "false"
  - arg:
      name: launch_no_stopping_area_module
      default: "true"
  - arg:
      name: launch_stop_line_module
      default: "true"
  - arg:
      name: launch_occlusion_spot_module
      default: "false"
  - arg:
      name: launch_run_out_module
      default: "true"
  - arg:
      name: launch_speed_bump_module
      default: "false"
  - arg:
      name: launch_out_of_lane_module
      default: "true"
  - arg:
      name: launch_no_drivable_lane_module
      default: "false"

  # motion planning modules
  - arg:
      name: motion_path_smoother_type
      default: elastic_band
      # option: elastic_band
      #         none

  - arg:
      name: motion_path_planner_type
      default: obstacle_avoidance_planner
      # option: obstacle_avoidance_planner
      #         path_sampler
      #         none

  - arg:
      name: motion_stop_planner_type
      default: obstacle_stop_planner
      # option: obstacle_stop_planner
      #         obstacle_cruise_planner
      #         none

  - arg:
      name: motion_velocity_smoother_type
      default: JerkFiltered
      # option: JerkFiltered
      #         L2
      #         Linf(Unstable)
      #         Analytical

  - arg:
      name: launch_surround_obstacle_checker
      default: "true"

  # parking modules
  - arg:
      name: launch_parking_module
      default: "true"
