/**:
  ros__parameters:
    dynamic_avoidance:
      # avoidance is performed for the object type with true
      target_object:
        car: true
        truck: true
        bus: true
        trailer: true
        unknown: false
        bicycle: false
        motorcycle: true
        pedestrian: false

        min_obstacle_vel: 1.0 # [m/s]

      drivable_area_generation:
        lat_offset_from_obstacle: 0.8 # [m]
        max_lat_offset_to_avoid: 0.5 # [m]

        # for same directional object
        overtaking_object:
          max_time_to_collision: 3.0 # [s]
          start_duration_to_avoid: 4.0  # [s]
          end_duration_to_avoid: 5.0  # [s]
          duration_to_hold_avoidance: 3.0 # [s]

        # for opposite directional object
        oncoming_object:
          max_time_to_collision: 3.0 # [s]
          start_duration_to_avoid: 9.0  # [s]
          end_duration_to_avoid: 0.0  # [s]
