/**:
  ros__parameters:
    lane_change:
      prepare_duration: 4.0         # [s]

      minimum_prepare_length: 2.0 # [m]
      minimum_lane_changing_length: 16.5          # [m]
      backward_length_buffer_for_end_of_lane: 3.0 # [m]
      lane_change_finish_judge_buffer: 2.0      # [m]

      lane_changing_lateral_jerk: 0.5              # [m/s3]
      lane_changing_lateral_acc: 0.315             # [m/s2]
      lane_changing_lateral_acc_at_low_velocity: 0.15 # [m/s2]
      lateral_acc_switching_velocity: 4.0          #[m/s]

      minimum_lane_changing_velocity: 2.78        # [m/s]
      prediction_time_resolution: 0.5           # [s]
      maximum_deceleration: 1.0                 # [m/s2]
      lane_change_sampling_num: 3

      # collision check
      enable_prepare_segment_collision_check: false
      prepare_segment_ignore_object_velocity_thresh: 0.1 # [m/s]
      use_predicted_path_outside_lanelet: false
      use_all_predicted_path: false

      # target object
      target_object:
        car: true
        truck: true
        bus: true
        trailer: true
        unknown: true
        bicycle: true
        motorcycle: true
        pedestrian: true

      # abort
      enable_cancel_lane_change: true
      enable_abort_lane_change: false

      abort_delta_time: 3.0                      # [s]
      abort_max_lateral_jerk: 1000.0             # [m/s3]

      # debug
      publish_debug_marker: false
